model_checkpoint:
  _target_: src.callbacks.model_checkpoint.MultiMetricTopKCheckpointCallback
  ckpt_dir: ${paths.output_dir}/checkpoints
  monitors: ["val/wmfcc", "val_nsynth/wmfcc"]
  modes: ["min", "min"]
  save_top_k: 5
  save_last: true

model_checkpoint_clap:
  _target_: src.callbacks.model_checkpoint.MultiMetricTopKCheckpointCallback
  ckpt_dir: ${paths.output_dir}/checkpoints
  monitors: ["val/clap", "val_nsynth/clap"]
  modes: ["min", "min"]
  save_top_k: 1
  save_last: false
