- MIDI_NOTE
- ALGORITHM
- FEEDBACK
- OSC KEY SYNC
- OP1 MODE
- OP1 F COARSE
- OP1 F FINE
- OP1 OSC DETUNE
- OP1 EG LEVEL 1
- OP1 EG LEVEL 2
- OP1 EG LEVEL 3
- OP1 EG LEVEL 4
- OP1 EG RATE 1
- OP1 EG RATE 2
- OP1 EG RATE 3
- OP1 EG RATE 4
- OP1 OUTPUT LEVEL
- OP1 A MOD SENS.
- OP2 MODE
- OP2 F COARSE
- OP2 F FINE
- OP2 OSC DETUNE
- OP2 EG LEVEL 1
- OP2 EG LEVEL 2
- OP2 EG LEVEL 3
- OP2 EG LEVEL 4
- OP2 EG RATE 1
- OP2 EG RATE 2
- OP2 EG RATE 3
- OP2 EG RATE 4
- OP2 OUTPUT LEVEL
- OP2 A MOD SENS.
- OP3 MODE
- OP3 F COARSE
- OP3 F FINE
- OP3 OSC DETUNE
- OP3 EG LEVEL 1
- OP3 EG LEVEL 2
- OP3 EG LEVEL 3
- OP3 EG LEVEL 4
- OP3 EG RATE 1
- OP3 EG RATE 2
- OP3 EG RATE 3
- OP3 EG RATE 4
- OP3 OUTPUT LEVEL
- OP3 A MOD SENS.
- OP4 MODE
- OP4 F COARSE
- OP4 F FINE
- OP4 OSC DETUNE
- OP4 EG LEVEL 1
- OP4 EG LEVEL 2
- OP4 EG LEVEL 3
- OP4 EG LEVEL 4
- OP4 EG RATE 1
- OP4 EG RATE 2
- OP4 EG RATE 3
- OP4 EG RATE 4
- OP4 OUTPUT LEVEL
- OP4 A MOD SENS.
- OP5 MODE
- OP5 F COARSE
- OP5 F FINE
- OP5 OSC DETUNE
- OP5 EG LEVEL 1
- OP5 EG LEVEL 2
- OP5 EG LEVEL 3
- OP5 EG LEVEL 4
- OP5 EG RATE 1
- OP5 EG RATE 2
- OP5 EG RATE 3
- OP5 EG RATE 4
- OP5 OUTPUT LEVEL
- OP5 A MOD SENS.
- OP6 MODE
- OP6 F COARSE
- OP6 F FINE
- OP6 OSC DETUNE
- OP6 EG LEVEL 1
- OP6 EG LEVEL 2
- OP6 EG LEVEL 3
- OP6 EG LEVEL 4
- OP6 EG RATE 1
- OP6 EG RATE 2
- OP6 EG RATE 3
- OP6 EG RATE 4
- OP6 OUTPUT LEVEL
- OP6 A MOD SENS.
- LFO WAVE
- LFO SPEED
- LFO DELAY
- LFO KEY SYNC
- P MODE SENS.
- LFO PM DEPTH
- LFO AM DEPTH
- PITCH EG LEVEL 1
- PITCH EG LEVEL 2
- PITCH EG LEVEL 3
- PITCH EG LEVEL 4
- PITCH EG RATE 1
- PITCH EG RATE 2
- PITCH EG RATE 3
- PITCH EG RATE 4
- MIDI_VELOCITY
- MIDI_DURATION
- EOS
