- OP6 EG RATE 2
- LFO PM DEPTH
- OP5 EG RATE 3
- OP4 EG RATE 1
- OP4 EG RATE 4
- OP2 A MOD SENS.
- OP1 EG LEVEL 3
- OP5 EG LEVEL 2
- OP3 EG RATE 1
- OP6 EG LEVEL 3
- OP1 EG RATE 2
- OP4 F FINE
- OP5 EG LEVEL 1
- OP5 MODE
- OP3 EG RATE 3
- OP1 EG LEVEL 2
- OP6 EG LEVEL 4
- OP5 EG RATE 2
- OP5 EG LEVEL 3
- OP1 EG LEVEL 1
- OP4 EG RATE 3
- OP2 EG RATE 2
- OP1 EG RATE 4
- OP6 EG LEVEL 1
- OP1 OUTPUT LEVEL
- PITCH EG RATE 2
- OP2 F COARSE
- OP4 OUTPUT LEVEL
- OP1 F COARSE
- OP2 EG LEVEL 3
- OP4 EG LEVEL 2
- OP5 F COARSE
- OP6 OUTPUT LEVEL
- OP6 EG RATE 4
- OP2 EG LEVEL 2
- OP2 EG RATE 4
- OP2 F FINE
- PITCH EG RATE 3
- OP4 EG LEVEL 3
- OP6 MODE
- OP5 OSC DETUNE
- OP3 EG LEVEL 1
- PITCH EG LEVEL 1
- OP2 EG RATE 1
- OP3 MODE
- OP6 EG RATE 1
- OP5 EG RATE 4
- OP1 A MOD SENS.
- OP4 EG LEVEL 1
- OP6 F FINE
- OP4 EG LEVEL 4
- OP2 EG LEVEL 1
- OP1 MODE
- OP2 MODE
- OP3 EG LEVEL 4
- OP6 A MOD SENS.
- OP6 EG LEVEL 2
- OP4 A MOD SENS.
- OP2 OUTPUT LEVEL
- OP5 A MOD SENS.
- MIDI_DURATION
- OP5 EG RATE 1
- OP6 F COARSE
- OP4 F COARSE
- OP6 EG RATE 3
- OP1 OSC DETUNE
- OP3 EG RATE 2
- OP1 EG LEVEL 4
- OP3 F COARSE
- OP4 EG RATE 2
- OP5 OUTPUT LEVEL
- OSC KEY SYNC
- OP3 A MOD SENS.
- OP3 EG LEVEL 3
- PITCH EG RATE 4
- OP3 OSC DETUNE
- OP3 OUTPUT LEVEL
- OP1 EG RATE 1
- OP2 OSC DETUNE
- OP5 F FINE
- PITCH EG LEVEL 2
- OP1 EG RATE 3
- OP6 OSC DETUNE
- OP2 EG RATE 3
- OP3 EG RATE 4
- PITCH EG RATE 1
- OP3 EG LEVEL 2
- OP1 F FINE
- OP3 F FINE
- OP4 MODE
- OP2 EG LEVEL 4
- OP5 EG LEVEL 4
- LFO SPEED
- MIDI_NOTE
- FEEDBACK
- LFO KEY SYNC
- LFO AM DEPTH
- LFO DELAY
- LFO WAVE
- P MODE SENS.
- ALGORITHM
- PITCH EG LEVEL 4
- PITCH EG LEVEL 3
- MIDI_VELOCITY
- OP4 OSC DETUNE
- EOS
