- MIDI_NOTE
- MIDI_VELOCITY
- MIDI_DURATION
- a_filter_configuration
- a_filter_balance
- a_fm_routing
- a_fm_depth
- a_highpass
- a_waveshaper_type
- a_waveshaper_drive
- a_feedback
- a_osc_drift
- a_pan
- a_width
- a_vca_gain
- a_osc_1_octave
- a_osc_1_pitch
- a_osc_1_sawtooth
- a_osc_1_pulse
- a_osc_1_triangle
- a_osc_1_width
- a_osc_1_sync
- a_osc_1_volume
- a_osc_1_route
- a_osc_1_mute
- a_osc_1_unison_voices
- a_osc_1_unison_detune
- a_osc_2_octave
- a_osc_2_pitch
- a_osc_2_sawtooth
- a_osc_2_pulse
- a_osc_2_triangle
- a_osc_2_width
- a_osc_2_sync
- a_osc_2_volume
- a_osc_2_route
- a_osc_2_mute
- a_osc_2_unison_voices
- a_osc_2_unison_detune
- a_osc_3_octave
- a_osc_3_pitch
- a_osc_3_sawtooth
- a_osc_3_pulse
- a_osc_3_triangle
- a_osc_3_width
- a_osc_3_sync
- a_osc_3_volume
- a_osc_3_route
- a_osc_3_mute
- a_osc_3_unison_voices
- a_osc_3_unison_detune
- a_noise_color
- a_noise_volume
- a_noise_route
- a_noise_mute
- a_ring_modulation_1x2_volume
- a_ring_modulation_1x2_route
- a_ring_modulation_1x2_mute
- a_ring_modulation_2x3_volume
- a_ring_modulation_2x3_route
- a_ring_modulation_2x3_mute
- a_filter_1_type
- a_filter_1_cutoff
- a_filter_1_resonance
- a_filter_1_feg_mod_amount
- a_filter_2_type
- a_filter_2_cutoff
- a_filter_2_resonance
- a_filter_2_feg_mod_amount
- a_amp_eg_attack
- a_amp_eg_decay
- a_amp_eg_sustain
- a_amp_eg_release
- a_amp_eg_envelope_mode
- a_filter_eg_attack
- a_filter_eg_decay
- a_filter_eg_sustain
- a_filter_eg_release
- a_filter_eg_envelope_mode
- a_lfo_1_type
- a_lfo_1_rate
- a_lfo_1_phase
- a_lfo_1_amplitude
- a_lfo_1_deform
- a_lfo_1_attack
- a_lfo_1_hold
- a_lfo_1_decay
- a_lfo_1_sustain
- a_lfo_1_release
- a_lfo_2_type
- a_lfo_2_rate
- a_lfo_2_phase
- a_lfo_2_amplitude
- a_lfo_2_deform
- a_lfo_2_attack
- a_lfo_2_hold
- a_lfo_2_decay
- a_lfo_2_sustain
- a_lfo_2_release
- a_lfo_3_type
- a_lfo_3_rate
- a_lfo_3_phase
- a_lfo_3_amplitude
- a_lfo_3_deform
- a_lfo_3_attack
- a_lfo_3_hold
- a_lfo_3_decay
- a_lfo_3_sustain
- a_lfo_3_release
- a_lfo_4_type
- a_lfo_4_rate
- a_lfo_4_phase
- a_lfo_4_amplitude
- a_lfo_4_deform
- a_lfo_4_attack
- a_lfo_4_hold
- a_lfo_4_decay
- a_lfo_4_sustain
- a_lfo_4_release
- a_lfo_5_type
- a_lfo_5_rate
- a_lfo_5_phase
- a_lfo_5_amplitude
- a_lfo_5_deform
- a_lfo_5_attack
- a_lfo_5_hold
- a_lfo_5_decay
- a_lfo_5_sustain
- a_lfo_5_release
- a_lfo_6_amplitude
- a_lfo_6_deform
- a_lfo_6_attack
- a_lfo_6_hold
- a_lfo_6_decay
- a_lfo_6_sustain
- a_lfo_6_release
- fx_a1_delay_time
- fx_a1_modulation_rate
- fx_a1_modulation_depth
- fx_a1_delay_feedback
- fx_a1_eq_low_cut
- fx_a1_eq_high_cut
- fx_a1_output_width
- fx_a1_output_mix
- fx_a2_delay_time_left
- fx_a2_delay_time_right
- fx_a2_feedback_eq_feedback
- fx_a2_feedback_eq_crossfeed
- fx_a2_feedback_eq_low_cut
- fx_a2_feedback_eq_high_cut
- fx_a2_modulation_rate
- fx_a2_modulation_depth
- fx_a2_input_channel
- fx_a2_output_width
- fx_a2_output_mix
- fx_a3_pre_delay_pre_delay
- fx_a3_reverb_room_size
- fx_a3_reverb_decay_time
- fx_a3_reverb_diffusion
- fx_a3_reverb_buildup
- fx_a3_reverb_modulation
- fx_a3_eq_lf_damping
- fx_a3_eq_hf_damping
- fx_a3_output_width
- fx_a3_output_mix
- EOS
